### ISSUE TITLE
Toggle -coverpkg flag

### ISSUE THREAD

**Issue by Omkar-Waingankar** [ncruces/go-coverage-report#15]
Hi! I wanted to propose adding a configuration knob to this action that would allow omitting the `-coverpkg` flag from `go test`. Using the `-coverpkg` flag is not necessarily desirable for computing coverage in all instances, especially if teams are laser focused on keeping the scope of their analysis within the package code itself. The toggle could look something like this

`coverpkg`: default `true`, use the `-coverpkg` flag when running `go test` to compute code coverage of a package

**Comment by ncruces** [comment]
OK.

If I'm going to allow configuring `coverpkg`, I think allowing you to decide the value is better than a `true`/`false` flag.

So how about making the default `module` (or something, that one [404s](https://pkg.go.dev/module)) for current behaviour, empty to disable it, anything else is passed through?

**Comment by ncruces** [comment]
But do note that it is _already_ possible to fix this on your side; just get the coverage you want by yourself, and then use this:
https://github.com/ncruces/go-coverage-report/blob/494b2847891f4dd3b10f6704ca533367dbb7493d/action.yml#L8-L9

All you need to do is run coverage _yourself_ before calling `go-coverage-report`, then set `coverage-file`:
```
go test ./... -coverpkg github.com/whoever/pkg -coverprofile coverage.out
```

**Comment by ncruces** [comment]
Generating coverage for the entire module seems like a reasonable zero configuration default, especially because the command to do it with zero configuration is _slightly_ complicated (most people won't know how).

Conversely, generating coverage for a single package is trivial. As we already support providing your own coverage file, that satisfies this and other (more complicated [^1]) use cases, I will close this as non-planed.

I'll focus the repo on generating badge, the coverage chart, and "serving" the HTML coverage report, since that's stuff most Go devs won't necessarily know how to do on their own in their GitHub actions.

[^1]: providing coverage from: multiple modules, specific packages, the same package under different `GOARCH`/`GOOS`/etc configurations, etc…
