### ISSUE TITLE
Support of private repos

### ISSUE THREAD

**Issue by dud225** [ncruces/go-coverage-report#9]
Hello
I've read that private repos are supported, however in my case even if _go-coverage-report_ worked fine, the GH wiki only allows the badge file to be retrieved, the HTML report always ends up with a `404 error not found`.

When checking out the wiki repo I do see all the files:
```
$ ls
coverage.html  coverage.log  coverage.svg  Home.md
```
but I'm not able to retrieve the HTML report nor the log file:
```
$ curl "https://raw.githubusercontent.com/wiki/dud225/myrepo/coverage.svg?token=<token retrieved from web browser> -I
HTTP/2 200
[...]
content-type: image/svg+xml

$ curl "https://raw.githubusercontent.com/wiki/dud225/myrepo/coverage.html?token=<token retrieved from web browser>" -I
HTTP/2 404
$ curl "https://raw.githubusercontent.com/wiki/dud225/myrepo/coverage.log?token=<token retrieved from web browser>" -I
HTTP/2 404
```

**Comment by ncruces** [comment]
_Welp_, that's definitely an issue.

The problem is the file is saved just fine on the Wiki, so even if it's available to you when authenticated, GitHub just refuses to render HTML files, on either the Wiki or repo. We need to use [GitHack](https://raw.githack.com/) to render these HTML files, and that's not going to work for private repos. See the difference between these links:

- https://github.com/ncruces/julianday/wiki/coverage.html
- https://raw.githack.com/wiki/ncruces/julianday/coverage.html

I don't have any private repos to test with cURL, so I can't be sure that's also the same issue.
I'm also not sure what I can do here.

I _could_ edit a markdown file on the wiki, but it will never be as detailed as the HTML coverage report. At best, it'd be the coverage % for every function.

**Comment by dud225** [comment]
That's fine I believe this is a limitation imposed by GH and it just needs to be mentioned on the doc.
